# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.remote_support_status import RemoteSupportStatus  # noqa: E501
from cohesivenet.rest import ApiException


class TestRemoteSupportStatus(unittest.TestCase):
    """RemoteSupportStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteSupportStatus(self):
        """Test RemoteSupportStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.remote_support_status.RemoteSupportStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
