# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response20072 import InlineResponse20072  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse20072(unittest.TestCase):
    """InlineResponse20072 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20072(self):
        """Test InlineResponse20072"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response20072.InlineResponse20072()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
