# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_response20023_response_parameters import InlineResponse20023ResponseParameters  # noqa: E501
from vns3api.rest import ApiException


class TestInlineResponse20023ResponseParameters(unittest.TestCase):
    """InlineResponse20023ResponseParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023ResponseParameters(self):
        """Test InlineResponse20023ResponseParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_response20023_response_parameters.InlineResponse20023ResponseParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
