# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_response20067 import InlineResponse20067  # noqa: E501
from vns3api.rest import ApiException


class TestInlineResponse20067(unittest.TestCase):
    """InlineResponse20067 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20067(self):
        """Test InlineResponse20067"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_response20067.InlineResponse20067()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
