# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_response20069 import InlineResponse20069  # noqa: E501
from vns3api.rest import ApiException


class TestInlineResponse20069(unittest.TestCase):
    """InlineResponse20069 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20069(self):
        """Test InlineResponse20069"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_response20069.InlineResponse20069()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
