# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_response20078_response_images import InlineResponse20078ResponseImages  # noqa: E501
from vns3api.rest import ApiException


class TestInlineResponse20078ResponseImages(unittest.TestCase):
    """InlineResponse20078ResponseImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20078ResponseImages(self):
        """Test InlineResponse20078ResponseImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_response20078_response_images.InlineResponse20078ResponseImages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
