# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.high_availability_api import HighAvailabilityApi  # noqa: E501
from openapi_client.rest import ApiException


class TestHighAvailabilityApi(unittest.TestCase):
    """HighAvailabilityApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.high_availability_api.HighAvailabilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ha_id(self):
        """Test case for get_ha_id

        """
        pass

    def test_get_ha_status(self):
        """Test case for get_ha_status

        """
        pass

    def test_get_ha_sync_file(self):
        """Test case for get_ha_sync_file

        """
        pass

    def test_get_ha_sync_status(self):
        """Test case for get_ha_sync_status

        """
        pass

    def test_post_init_ha(self):
        """Test case for post_init_ha

        """
        pass

    def test_post_sync_ha(self):
        """Test case for post_sync_ha

        """
        pass

    def test_put_ha_activate(self):
        """Test case for put_ha_activate

        """
        pass

    def test_put_ha_push_file(self):
        """Test case for put_ha_push_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
