# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response20038_response import InlineResponse20038Response  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse20038Response(unittest.TestCase):
    """InlineResponse20038Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20038Response(self):
        """Test InlineResponse20038Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response20038_response.InlineResponse20038Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
