# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response20087 import InlineResponse20087  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse20087(unittest.TestCase):
    """InlineResponse20087 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20087(self):
        """Test InlineResponse20087"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response20087.InlineResponse20087()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
