# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_response20082_response_state import InlineResponse20082ResponseState  # noqa: E501
from vns3api.rest import ApiException


class TestInlineResponse20082ResponseState(unittest.TestCase):
    """InlineResponse20082ResponseState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20082ResponseState(self):
        """Test InlineResponse20082ResponseState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_response20082_response_state.InlineResponse20082ResponseState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
