# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.create_access_url_request import CreateAccessURLRequest  # noqa: E501
from cohesivenet.rest import ApiException


class TestCreateAccessURLRequest(unittest.TestCase):
    """CreateAccessURLRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAccessURLRequest(self):
        """Test CreateAccessURLRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.create_access_url_request.CreateAccessURLRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
