# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response2008_response import InlineResponse2008Response  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse2008Response(unittest.TestCase):
    """InlineResponse2008Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008Response(self):
        """Test InlineResponse2008Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response2008_response.InlineResponse2008Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
