# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.ec2_cloud_info import EC2CloudInfo  # noqa: E501
from openapi_client.rest import ApiException


class TestEC2CloudInfo(unittest.TestCase):
    """EC2CloudInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEC2CloudInfo(self):
        """Test EC2CloudInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.ec2_cloud_info.EC2CloudInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
