# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_object40 import InlineObject40  # noqa: E501
from vns3api.rest import ApiException


class TestInlineObject40(unittest.TestCase):
    """InlineObject40 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject40(self):
        """Test InlineObject40"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_object40.InlineObject40()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
