# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_response20026_response_history import InlineResponse20026ResponseHistory  # noqa: E501
from vns3api.rest import ApiException


class TestInlineResponse20026ResponseHistory(unittest.TestCase):
    """InlineResponse20026ResponseHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026ResponseHistory(self):
        """Test InlineResponse20026ResponseHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_response20026_response_history.InlineResponse20026ResponseHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
