# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.models.inline_object10 import InlineObject10  # noqa: E501
from vns3api.rest import ApiException


class TestInlineObject10(unittest.TestCase):
    """InlineObject10 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject10(self):
        """Test InlineObject10"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vns3api.models.inline_object10.InlineObject10()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
