# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API for configuring and retrieving VNS3 controller  # noqa: E501

    The version of the OpenAPI document: 4.7
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vns3api
from vns3api.routing_api import RoutingApi  # noqa: E501
from vns3api.rest import ApiException


class TestRoutingApi(unittest.TestCase):
    """RoutingApi unit test stubs"""

    def setUp(self):
        self.api = vns3api.routing_api.RoutingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_route(self):
        """Test case for delete_route

        """
        pass

    def test_get_routes(self):
        """Test case for get_routes

        """
        pass

    def test_post_create_route(self):
        """Test case for post_create_route

        """
        pass


if __name__ == '__main__':
    unittest.main()
