# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.vns3_controller_peer import VNS3ControllerPeer  # noqa: E501
from cohesivenet.rest import ApiException


class TestVNS3ControllerPeer(unittest.TestCase):
    """VNS3ControllerPeer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVNS3ControllerPeer(self):
        """Test VNS3ControllerPeer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.vns3_controller_peer.VNS3ControllerPeer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
