# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.firewall_subgroup_list_response import FirewallSubgroupListResponse  # noqa: E501
from cohesivenet.rest import ApiException


class TestFirewallSubgroupListResponse(unittest.TestCase):
    """FirewallSubgroupListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFirewallSubgroupListResponse(self):
        """Test FirewallSubgroupListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.firewall_subgroup_list_response.FirewallSubgroupListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
