# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.clientpack_tag_key_request import (
    ClientpackTagKeyRequest,
)  # noqa: E501
from cohesivenet.rest import ApiException


class TestClientpackTagKeyRequest(unittest.TestCase):
    """ClientpackTagKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientpackTagKeyRequest(self):
        """Test ClientpackTagKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.clientpack_tag_key_request.ClientpackTagKeyRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
