# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.firewall_fw_set_list_response import (
    FirewallFWSetListResponse,
)  # noqa: E501
from cohesivenet.rest import ApiException


class TestFirewallFWSetListResponse(unittest.TestCase):
    """FirewallFWSetListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFirewallFWSetListResponse(self):
        """Test FirewallFWSetListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.firewall_fw_set_list_response.FirewallFWSetListResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
