# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.running_containers_detail import (
    RunningContainersDetail,
)  # noqa: E501
from cohesivenet.rest import ApiException


class TestRunningContainersDetail(unittest.TestCase):
    """RunningContainersDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunningContainersDetail(self):
        """Test RunningContainersDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.running_containers_detail.RunningContainersDetail()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
