# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.models.container_image_list_response import ContainerImageListResponse  # noqa: E501
from cohesivenet.rest import ApiException


class TestContainerImageListResponse(unittest.TestCase):
    """ContainerImageListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerImageListResponse(self):
        """Test ContainerImageListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cohesivenet.models.container_image_list_response.ContainerImageListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
