# coding: utf-8

"""
    VNS3 Controller API

    Cohesive networks VNS3 API providing complete control of your network's addresses, routes, rules and edge  # noqa: E501

    The version of the OpenAPI document: 4.8
    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cohesivenet
from cohesivenet.api.vns3.configuration_api import ConfigurationApi  # noqa: E501
from cohesivenet.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = cohesivenet.api.vns3.configuration_api.ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config(self):
        """Test case for get_config

        """
        pass

    def test_get_keyset(self):
        """Test case for get_keyset

        """
        pass

    def test_get_runtime(self):
        """Test case for get_runtime

        """
        pass

    def test_get_ssl_install_status(self):
        """Test case for get_ssl_install_status

        """
        pass

    def test_put_config(self):
        """Test case for put_config

        """
        pass

    def test_put_install_ssl_keypair(self):
        """Test case for put_install_ssl_keypair

        """
        pass

    def test_put_keyset(self):
        """Test case for put_keyset

        """
        pass

    def test_put_update_admin_ui(self):
        """Test case for put_update_admin_ui

        """
        pass

    def test_put_update_api_password(self):
        """Test case for put_update_api_password

        """
        pass

    def test_put_upload_ssl_keypair(self):
        """Test case for put_upload_ssl_keypair

        """
        pass


if __name__ == "__main__":
    unittest.main()
