# coding: utf-8

"""
    VNS3:ms API

    Cohesive networks VNS3 provides complete control of your network's addresses, routes, rules and edge. Networking does  # noqa: E501

    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

from cohesivenet.api_builder import VersionRouter


class UserApiRouter(VersionRouter):
    """User management endpoints for configuring credentials"""

    function_library = {
        "put_user_password": {"2.1.1": None},
        "get_validate_username": {"2.1.1": None},
        "get_validate_email": {"2.1.1": None},
        "get_user_credentials": {"2.1.1": None},
        "post_create_user_credentials": {"2.1.1": None},
        "put_update_user_credentials": {"2.1.1": None},
        "delete_user_credentials": {"2.1.1": None}
    }