 # coding: utf-8

"""
    VNS3:ms API

    Cohesive networks VNS3 provides complete control of your network's addresses, routes, rules and edge. Networking does  # noqa: E501

    Contact: solutions@cohesive.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

from cohesivenet.api_builder import VersionRouter


class VNS3ManagementApiRouter(VersionRouter):
    """Manage VNS3 controllers in your network topology, automating snapshots, HA and more"""

    function_library = {
        "get_vns3_snapshots": {"2.1.1": None},
        "post_create_vns3_snapshot": {"2.1.1": None},
        "delete_vns3_snapshot": {"2.1.1": None},
        "get_download_vns3_snapshot": {"2.1.1": None},
        "get_controller_report": {"2.1.1": None},
        "get_vns3_controllers": {"2.1.1": None},
        "post_add_vns3_controller": {"2.1.1": None},
        "get_vns3_controller": {"2.1.1": None},
        "put_update_vns3_controller": {"2.1.1": None},
        "delete_vns3_controller": {"2.1.1": None},
        "get_vns3_controller_status": {"2.1.1": None},
        "put_vns3_controller_api_password": {"2.1.1": None},
        "put_vns3_controller_ui": {"2.1.1": None},
        "get_vns3_controller_ha_details": {"2.1.1": None},
        "put_update_vns3_controller_ha": {"2.1.1": None},
        "put_validate_vns3_controller_ha": {"2.1.1": None},
        "put_init_vns3_controller_ha": {"2.1.1": None},
        "put_sync_vns3_controller_ha": {"2.1.1": None},
        "get_vns3_controller_ha_status": {"2.1.1": None},
        "put_activate_vns3_controller_ha": {"2.1.1": None},
    }